import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import 'boxicons/css/boxicons.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Emergency dispacth system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
